export * from "./MainTitle";
export * from "./NameForReview";
export * from "./Paragraph";
export * from "./ParagraphForCards";
export * from "./TextAreaFormComponent";
export * from "./BoldParagraph";
export * from "./FooterTextLogo";
export * from "./TextForHeaderBasketIcon";
export * from "./normal";
