export const CHANGE_RANGE_MIN_VALUE = "CHANGE_RANGE_MIN";
export const CHANGE_RANGE_MAX_VALUE = "CHANGE_RANGE_MAX";
export const CHANGE_SELECTED_FILTER = "CHANGE_SELECTED_FITER";
export const CHANGE_SEARCH_FILTER = "CHANGE_SEARCH_FITER";