export const ADD_THE_REVIEW = "ADD_THE_REVIEW";
export const GET_REVIEWS = "GET_REVIEWS";
export const OPEN_MODAL_REVIEW = "OPEN_MODAL_REVIEW";
export const CLOSE_MODAL_REVIEW = "CLOSE_MODAL_REVIEW";
export const SET_SENDING_STATE_LOADING = "SET_SENDING_STATE_LOADING";
export const SET_SENDING_STATE_DONE = "SET_SENDING_STATE_DONE";
export const SET_SUCCESS_SENDING_STATE_DONE = "SET_SUCCESS_SENDING_STATE_DONE";
export const RESET_SUCCESS_SENDING_STATE_DONE = "RESET_SUCCESS_SENDING_STATE_DONE";
